### PR TITLE
Small refactoring on eShopOnBlazor project

### PR DESCRIPTION
**Pull request by vishipayyallore**

### CODE REVIEW

**Comment by vishipayyallore** [comment]
Sumit - @sughosneo 
Good evening. I have a small PR. Could you please look into this whenever you get a couple of minutes? Many thanks.

Regards,
Swamy

**Comment by sughosneo** [comment]
Hi @vishipayyallore , thank you for submitting this PR. LGTM

Pinging @csharpfritz / @danroth27 - for further review and feedback.

**Comment by vishipayyallore** [comment]
@csharpfritz @danroth27 
Good morning. Happy Holidays.

**Comment by vishipayyallore** [comment]
@csharpfritz @danroth27
Good morning. Could you please look into this whenever you get a few minutes? Many thanks.

Regards,
Swamy

**Comment by vishipayyallore** [comment]
Sumit - @sughosneo 
Good evening.

**Comment by csharpfritz** [comment]
I don’t see any significant changes to the sample other than organizing the using statements. 




Jeff

**Comment by vishipayyallore** [comment]
@csharpfritz 
Good morning. I will do some more changes and raise another PR.

**Pull request closed without merging**
